version: '3.8'
volumes:
  elasticdata:
    driver: local
  postgres-data:
    driver: local
  redis: {}
networks:
  app_network:
    driver: bridge
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    # ports:
    #   - "3000:3000"
    networks:
      - app_network
    # The app container needs to know about other services
    extra_hosts:
      - "localhost:172.17.0.1"
      - "host.docker.internal:host-gateway"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    environment:
      - node.name=elastic
      - cluster.name=es-cluster
      - bootstrap.memory_lock=false       # Changed to false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"  # Reduced memory requirements
      - discovery.type=single-node        # Add this for single-node setup
      - http.cors.enabled=true
      - http.cors.allow-origin=/.*/
      - network.host=0.0.0.0
      - xpack.security.enabled=false           # Disable security features
      - xpack.security.http.ssl.enabled=false  # Disable HTTPS
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - app_network
    extra_hosts:
      - "localhost:172.17.0.1"
      - "host.docker.internal:host-gateway"
  memcached:
    image: memcached:latest
    container_name: my-memcached
    ports:
      - "11211:11211"
    command: memcached -m 64    # Allocate 64MB of memory
    restart: unless-stopped
    networks:
      - app_network
    extra_hosts:
      - "localhost:172.17.0.1"
      - "host.docker.internal:host-gateway"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - app_network
    extra_hosts:
      - "localhost:172.17.0.1"
      - "host.docker.internal:host-gateway"
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - app_network
    extra_hosts:
      - "localhost:172.17.0.1"
      - "host.docker.internal:host-gateway"
